name: Unittests

on: push

jobs:
  # prepare-notebooktest:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     matrix: ${{ steps.set-matrix.outputs.matrix }}
  #   steps:
  #   - uses: actions/checkout@v2
  #   # Set up the matrix for notebooktest-job which contains all notebooks to test.
  #   - id: set-matrix
  #     run: echo "::set-output name=matrix::$(ls docs/*ipynb | jq -R -s -c 'split("\n")[:-1]')"

  notebooktest-job:
    name: "Notebook tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        notebook: ${{ fromJson(needs.prepare-notebooktest.outputs.matrix) }}
        exclude:
          - notebook: docs/determinism.ipynb
      # Do not cancel in-progress jobs if any other matrix jobs fails.
      fail-fast: false

    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v2

    # Install deps.
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip --version
    - run: pip install tf-nightly
    - run: pip install ipython
    - run: sudo apt install -y protobuf-compiler

    - run: pip install -e .[tests-all]

    # Separately test each notebook.
    - name: Run notebook
      run: |
        ipython kernel install --user --name tfds-notebook
        for notebook in docs/*ipynb
          do
          jupyter nbconvert \
            --ExecutePreprocessor.timeout=600 \
            --ExecutePreprocessor.kernel_name=tfds-notebook \
            --to notebook \
            --execute $notebook
          done
