name: Unittests

on: push

jobs:
  pytest-job:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v2

    # Install deps
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - run: pip --version
    - run: pip install -e .[tests-all]
    - run: pip install tensorflow

    # Run tests
    - name: Run core tests
      run: pytest -vv -n auto

    - run: echo "test completed"
